vscode:
  extensions:
    - formulahendry.vscode-mysql@0.4.0:IAUm3OoC/011qAjawyOjqw==
    - DavidAnson.vscode-markdownlint@0.37.0:JsyciBGHwqfyaOd093YHWQ==
    - felixfbecker.php-intellisense@2.3.14:FMIUPy0FlHl+kH1Df7LR2A==
    - rifi2k.format-html-in-php@1.6.3:tzjzvW6RVquuisGt4fKBHw==